### ISSUE TITLE
Mutation is miRNA gene

### ISSUE THREAD

**Issue by s-a-nersisyan** [bcgsc/mirna#7]
Hello!

I am analyzing TCGA miRNA-seq data processed with BCGSC miRNA algorithm. As I can understand from the documentation and the original paper, the algorithm counts only exact matches between reads and known miRNA sequences. Does this mean that if a particular patient had a mutation in some miRNA this will affect miRNA expression very much? Specifically, for heterozygous patients (one canonical, one mutated) we would observe a half of total expression, and mismatches on both chromosomes would lead to near zero expression (near zero instead of completely zero since some RNA-level editing is theoretically possible and can "fix" the mismatch)? If my thoughts are correct, this can negatively affect many studies which involve correlation analysis. Thank you!

**Comment by AGordonRobertson** [comment]
Stephan

Your understanding matches mine — only exact-match read alignments are counted towards expression, so variants in a sample’s DNA (and edits in the expressed RNA) will result in a read NOT being counted towards ‘expression’, for that sample. The read should be retained in the BAM file, and we have in a small number of cases retrieved such reads and have analyzed them for RNA edits. E.g. Velazquez-Torres G, et al. A-to-I miR-378a-3p editing can prevent melanoma progression via regulation of PARVA expression. Nat Commun. 2018 Jan 31;9(1):461.

It’s worth also considering miRNA families that can express a mature strand from more than one genomic location, and issues around the (older) version of BWA that was used in TCGA. See PMID: 31344359.

Gordon
—
Gordon Robertson
Staff scientist
BC Cancer
Vancouver Canada


On Dec 8, 2020, at 11:56, Stepan Nersisyan <notifications@github.com<mailto:notifications@github.com>> wrote:



Hello!

I am analyzing TCGA miRNA-seq data processed with BCGSC miRNA algorithm. As I can understand from the documentation and the original paper, the algorithm counts only exact matches between reads and known miRNA sequences. Does this mean that if a particular patient had a mutation in some miRNA this will affect miRNA expression very much? Specifically, for heterozygous patients (one canonical, one mutated) we would observe a half of total expression, and mismatches on both chromosomes would lead to near zero expression (some RNA-level editing is theoretically possible and can "fix" the mismatch)? If my thoughts are correct, this can negatively affect many studies which involve correlation analysis. Thank you!

**Comment by s-a-nersisyan** [comment]
Thank you very much, Gordon! This information is really important in miRNA expression analysis, however, is ignored by the majority of researchers.
